# Generated by Django 5.2.7 on 2025-10-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('categories', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('banner_image', models.ImageField(blank=True, default='fallback.png', upload_to='blog_banners/')),
            ],
        ),
    ]
