# Generated by Django 5.2.7 on 2025-10-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categories',
            new_name='category',
        ),
    ]
