# Generated by Django 5.2.7 on 2025-10-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_categories_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='fallback_thumb.png', upload_to='blog_thumbnails/'),
        ),
    ]
