# Generated by Django 5.2.7 on 2025-10-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
